<?php

namespace FantasyPro\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContestEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContestEntryRepository extends EntityRepository
{
    public function findAllByUser( $user )
    {
        $query = $this->createQueryBuilder( 'u' )
                      ->select( 'u' )
                      ->Where( ':user = u.user' )
                      ->setParameter( 'user', $user );

        return $query->getQuery()->getResult();
    }
}
