<?php

namespace FantasyPro\GameBundle\Entity;

/**
 * ContestStyleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContestStyleRepository extends \Doctrine\ORM\EntityRepository
{
}
