<?php

namespace FantasyPro\GameBundle\Entity;

/**
 * EntryFeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryFeeRepository extends \Doctrine\ORM\EntityRepository
{
}
