<?php

namespace FantasyPro\GameBundle\Entity;

/**
 * PayoutStructureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayoutStructureRepository extends \Doctrine\ORM\EntityRepository
{
}
