<?php

namespace FantasyPro\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ScheduleGroupRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ScheduleGroupRepository extends EntityRepository
{
    public function getScheduleGroup( $id )
    {
        //get the games in this schedulegroup
        $schedules = $this->find( $id )->getSchedules();

        return $schedules;
    }
}
